main: me.RockinChaos.signutils.SignUtils
version: ${project.version}-b${env.BUILD_NUMBER}
name: SignUtils
author: RockinChaos
load: POSTWORLD
api-version: 1.13
description: Create custom utility signs.
website: https://www.spigotmc.org/resources/signutils.66019/
softdepend: [BetterNick, PlaceholderAPI, Vault]

permissions:
   signutils.*:
      description: Allows use of all commands and utility signs.
      default: false
      children:
          signutils.all: true
   signutils.all:
      description: Allows use of all commands and utility signs.
      default: false
      children:
          signutils.use: true
          signutils.reload: true
          signutils.updates: true
          signutils.upgrade: true
          signutils.rank: true
          signutils.rank.others: true
          signutils.create: true
   signutils.use:
      description: Allows the use of basic plugin commands.
      default: true
   signutils.reload:
      description: Allows the use of the reload command.
      default: false
   signutils.rank:
      description: Allows the user to use the rank command.
      default: false
   signutils.rank.others:
      description: Allows the user to use the rank command for other players.
      default: false
   signutils.updates:
      description: Allows the use of the updates command.
      default: false
   signutils.upgrade:
      description: Allows the use of the autoupdate command.
      default: false
   signutils.create:
      description: Allows the user to create custom utility signs.
      default: false
      
commands:
   signutils:
      description: Displays a menu giving credit to the creator and the help menu command.
      permission: signutils.use
      aliases: [su]
      usage: |
          /signutils
          Example: /signutils