# --{ =-=-=-=-=-=-=-=-=-=-=-= SignUtils Configuration Settings, by RockinChaos =-=-=-=-=-=-=-=-=-=-=-= }--
# See the tutorial page for a more in-depth explaination; https://github.com/RockinChaos/SignUtils/wiki
config-Version: 1

# English is currently the only support language at the moment!
Language: 'English'


# These are typically general maintenance settings that do not affect functionality.
General:
  CheckforUpdates: true
  Metrics-Logging: true
  Debugging: false
  
# These permissions if enabled, determine whether the permission(s) is/are applied to certain players.
Permissions:
  Commands-OP: false